double-jump-enabled: true

enderbutt:
  enabled: true
  item:
    type: 'ENDER_PEARL'
    name: '&eEnderbutt &7(Right Click)'
    slot: 5
    amount: 1

queue-message-delay: 30

launchpad-enabled: true
launchpad-type: STONE_PLATE

void-level: -1